# Generated by Django 5.2.17 on 2026-08-19 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Osobno vozilo'), ('VAN', 'Kombi'), ('TRUCK', 'Kamion'), ('BUS', 'Autobus'), ('TRACTOR', 'Traktor'), ('EXCAVATOR', 'Bager'), ('LOADER', 'Utovarivač'), ('FORKLIFT', 'Viličar'), ('OTHER', 'Ostalo')], max_length=20)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('production_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=30)),
                ('vin_serial_number', models.CharField(blank=True, max_length=100)),
                ('fuel_type', models.CharField(blank=True, choices=[('PETROL', 'Benzin'), ('DIESEL', 'Dizel'), ('HYBRID', 'Hibrid'), ('PHEV', 'Plug-in hibrid'), ('ELECTRIC', 'Električno'), ('LPG', 'LPG'), ('CNG', 'CNG'), ('OTHER', 'Ostalo')], max_length=20)),
                ('current_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('working_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Ispravno'), ('IN_SERVICE', 'U servisu'), ('OUT_OF_ORDER', 'Neispravno')], default='OPERATIONAL', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
