# Generated by Django 5.2.17 on 2026-08-23 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('VEHICLE_CREATED', 'Dodano vozilo / stroj'), ('VEHICLE_UPDATED', 'Ažurirano vozilo / stroj'), ('VEHICLE_STATUS_CHANGED', 'Promijenjen status vozila / stroja'), ('MAINTENANCE_CREATED', 'Dodano održavanje'), ('MAINTENANCE_UPDATED', 'Ažurirano održavanje'), ('REGISTRATION_CREATED', 'Dodana registracija / tehnički pregled'), ('REGISTRATION_UPDATED', 'Ažurirana registracija / tehnički pregled'), ('DOCUMENT_CREATED', 'Dodan dokument'), ('DOCUMENT_UPDATED', 'Ažuriran dokument'), ('VEHICLE_DELETED', 'Obrisano vozilo / stroj'), ('MAINTENANCE_DELETED', 'Obrisano održavanje'), ('REGISTRATION_DELETED', 'Obrisana registracija / tehnički pregled'), ('DOCUMENT_DELETED', 'Obrisan dokument')], max_length=40)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Aktivnost',
                'verbose_name_plural': 'Aktivnosti',
                'ordering': ['-created_at'],
            },
        ),
    ]
