# Generated by Django 5.2.17 on 2026-08-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='level',
            field=models.CharField(choices=[('INFO', 'Informacija'), ('WARNING', 'Upozorenje')], default='INFO', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('VEHICLE_CREATED', 'Dodano vozilo / stroj'), ('VEHICLE_UPDATED', 'Ažurirano vozilo / stroj'), ('VEHICLE_STATUS_CHANGED', 'Promijenjen status vozila / stroja'), ('VEHICLE_DELETED', 'Obrisano vozilo / stroj'), ('MAINTENANCE_CREATED', 'Dodano održavanje'), ('MAINTENANCE_UPDATED', 'Ažurirano održavanje'), ('MAINTENANCE_DELETED', 'Obrisano održavanje'), ('REGISTRATION_CREATED', 'Dodana registracija / tehnički pregled'), ('REGISTRATION_UPDATED', 'Ažurirana registracija / tehnički pregled'), ('REGISTRATION_DELETED', 'Obrisana registracija / tehnički pregled'), ('DOCUMENT_CREATED', 'Dodan dokument'), ('DOCUMENT_UPDATED', 'Ažuriran dokument'), ('DOCUMENT_DELETED', 'Obrisan dokument')], max_length=40),
        ),
    ]
