# Generated by Django 5.2.17 on 2026-08-25 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_is_read_activity_level_and_more'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('VEHICLE_CREATED', 'Dodano vozilo / stroj'), ('VEHICLE_UPDATED', 'Ažurirano vozilo / stroj'), ('VEHICLE_STATUS_CHANGED', 'Promijenjen status vozila / stroja'), ('VEHICLE_DELETED', 'Obrisano vozilo / stroj'), ('MAINTENANCE_CREATED', 'Dodano održavanje'), ('MAINTENANCE_UPDATED', 'Ažurirano održavanje'), ('MAINTENANCE_DELETED', 'Obrisano održavanje'), ('REGISTRATION_CREATED', 'Dodana registracija / tehnički pregled'), ('REGISTRATION_UPDATED', 'Ažurirana registracija / tehnički pregled'), ('REGISTRATION_DELETED', 'Obrisana registracija / tehnički pregled'), ('DOCUMENT_CREATED', 'Dodan dokument'), ('DOCUMENT_UPDATED', 'Ažuriran dokument'), ('DOCUMENT_DELETED', 'Obrisan dokument'), ('MAINTENANCE_REMINDER', 'Podsjetnik za održavanje'), ('REGISTRATION_REMINDER', 'Podsjetnik za registraciju'), ('TECHNICAL_INSPECTION_REMINDER', 'Podsjetnik za tehnički pregled')], max_length=40),
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('MAINTENANCE', 'Održavanje'), ('REGISTRATION', 'Registracija'), ('TECHNICAL_INSPECTION', 'Tehnički pregled')], max_length=30)),
                ('object_id', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('days_before', models.PositiveSmallIntegerField()),
                ('activity_created', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_logs', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Evidencija podsjetnika',
                'verbose_name_plural': 'Evidencije podsjetnika',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'reminder_type', 'object_id', 'due_date', 'days_before'), name='unique_due_reminder')],
            },
        ),
    ]
