# Generated by Django 5.2.17 on 2026-08-20 14:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('maintenance_type', models.CharField(choices=[('REGULAR_SERVICE', 'Redovni servis'), ('MAJOR_SERVICE', 'Veliki servis'), ('OIL_CHANGE', 'Zamjena ulja'), ('REPAIR', 'Popravak'), ('TIRES', 'Gume'), ('DIAGNOSTICS', 'Dijagnostika'), ('OTHER', 'Ostalo')], max_length=30)),
                ('status', models.CharField(choices=[('PLANNED', 'Planirano'), ('IN_PROGRESS', 'U tijeku'), ('COMPLETED', 'Završeno'), ('CANCELED', 'Otkazano')], default='PLANNED', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('service_provider', models.CharField(blank=True, max_length=150)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('working_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.TextField(blank=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('next_service_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('next_service_working_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
