# Generated by Django 5.2.17 on 2026-08-21 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('document_type', models.CharField(choices=[('REGISTRATION', 'Prometna dozvola'), ('INSURANCE', 'Polica osiguranja'), ('TECHNICAL', 'Tehnička dokumentacija'), ('SERVICE', 'Servisna dokumentacija'), ('PURCHASE', 'Dokumentacija o kupnji'), ('WARRANTY', 'Jamstvo'), ('OTHER', 'Ostalo')], max_length=30)),
                ('file', models.FileField(upload_to='vehicle_documents/')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
