# Generated by Django 5.2.17 on 2026-08-21 12:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('REGISTRATION', 'Registracija'), ('TECHNICAL_INSPECTION', 'Tehnički pregled')], max_length=30)),
                ('date', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=150)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('working_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_inspections', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
